"""initial postgres schema

Revision ID: 2cb3fba87cc2
Revises: 
Create Date: 2026-06-14 15:22:22.232894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cb3fba87cc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pubmed_id', sa.String(), nullable=True),
    sa.Column('pmc_id', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('openalex_id', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('study_type', sa.String(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mesh_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('full_text_available', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi'),
    sa.UniqueConstraint('openalex_id'),
    sa.UniqueConstraint('pmc_id'),
    sa.UniqueConstraint('pubmed_id')
    )
    op.create_table('book_sections',
    sa.Column('accession_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_text_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ssh_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ssh_key')
    )
    op.create_table('web_search_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intake_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medical_summary', sa.Text(), nullable=True),
    sa.Column('raw_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pmh', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('family_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('social', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medical_summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('research_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intake_session_id', sa.Uuid(), nullable=False),
    sa.Column('research_report', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_articles',
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('citation_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_book_sections',
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('book_section_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citation_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_section_id'], ['book_sections.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_web_search_results',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('web_search_result_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citation_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ),
    sa.ForeignKeyConstraint(['web_search_result_id'], ['web_search_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_web_search_results')
    op.drop_table('session_book_sections')
    op.drop_table('session_articles')
    op.drop_table('research_sessions')
    op.drop_table('user_profile')
    op.drop_table('intake_sessions')
    op.drop_table('web_search_results')
    op.drop_table('users')
    op.drop_table('book_sections')
    op.drop_table('articles')
    # ### end Alembic commands ###
