"""remove circular fk doctor_session_id from chat_sessions

Revision ID: 64ae099330ec
Revises: 81bd86e34e0a
Create Date: 2026-06-21 21:33:04.783471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ae099330ec'
down_revision: Union[str, Sequence[str], None] = '81bd86e34e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_sessions_doctor_session_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'doctor_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('doctor_session_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chat_sessions_doctor_session_id_fkey'), 'chat_sessions', 'doctor_sessions', ['doctor_session_id'], ['id'])
    # ### end Alembic commands ###
