"""create session and doctor models

Revision ID: 81bd86e34e0a
Revises: d8aebad3454a
Create Date: 2026-06-21 21:26:03.985098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81bd86e34e0a'
down_revision: Union[str, Sequence[str], None] = 'd8aebad3454a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intake_session_id', sa.Uuid(), nullable=True),
    sa.Column('research_session_id', sa.Uuid(), nullable=True),
    sa.Column('doctor_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], ),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('chat_sessions_doctor_session_id_fkey', 'chat_sessions', 'doctor_sessions', ['doctor_session_id'], ['id'])
    op.drop_table('user_sessions')
    op.add_column('intake_sessions', sa.Column('thread_id', sa.String(), nullable=True))
    op.drop_column('intake_sessions', 'raw_transcript')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake_sessions', sa.Column('raw_transcript', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('intake_sessions', 'thread_id')
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('intake_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('research_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], name=op.f('user_sessions_intake_session_id_fkey')),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.id'], name=op.f('user_sessions_research_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey'))
    )
    op.drop_constraint('chat_sessions_doctor_session_id_fkey', 'chat_sessions', type_='foreignkey')
    op.drop_table('doctor_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
