"""idk

Revision ID: d8aebad3454a
Revises: a1b2c3d4e5f6
Create Date: 2026-06-17 17:18:43.373437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8aebad3454a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intake_session_id', sa.Uuid(), nullable=True),
    sa.Column('research_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], ),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('research_sessions', 'intake_session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_sessions', 'intake_session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
