"""add research session trigger and effort

Revision ID: e929d8b95384
Revises: 0261496b4ea9
Create Date: 2026-06-27 18:12:45.422909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e929d8b95384'
down_revision: Union[str, Sequence[str], None] = '0261496b4ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_sessions', sa.Column('triggered_by', sa.String(), server_default='user', nullable=False))
    op.add_column('research_sessions', sa.Column('research_effort', sa.String(), server_default='standard', nullable=False))
    op.alter_column('research_sessions', 'triggered_by', server_default=None)
    op.alter_column('research_sessions', 'research_effort', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_sessions', 'research_effort')
    op.drop_column('research_sessions', 'triggered_by')
    # ### end Alembic commands ###
